config/routes.rb
Higashinoterakoya::Application.routes.draw do

  get "special_contents/index"

  get "about_us/index"

  get "history/index"

  get "archives/index"

  get "admin" => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :articles do
    get :who_written, on: :member
  end

  get "links/index"

  get "staff/index"

  get "products/index"

  resources :history
  resources :about_us
  resources :products
  resources :staff
  resources :links
  resources :archives
  get "information/index"

   root :to => 'information#index', as: 'information'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :description, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  attr_accessible :name, :password, :password_confirmation, :special_password
  has_secure_password
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  skip_before_filter :authorize
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  skip_before_filter :authorize
  def index
    @articles = Article.order("created_at DESC").limit(10)
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("created_at DESC")

    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    begin
    @article = Article.find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    rescue ActiveRecord::RecordNotFound
      logger.error "invalid page#{params[:id]}"
      redirect_to '/'
    else
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  skip_before_filter :authorize
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  skip_before_filter :authorize
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize
  def index
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  skip_before_filter :authorize
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  skip_before_filter :authorize, only: [:create, :new, :update, :show]
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User#{@user.name} was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User#{@user.name} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    Redcarpet.new(text, *options).to_html.html_safe
  end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_async_current.html.erb
<%= @time %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
    

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/async_process.js.erb
$('#async').text("");

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= link_to '新しく記事を書く', new_article_path, :class => 'btn btn-large' %>
<% @articles.each do |article| %>
  <tr>
    <p>
    
      <h2>
        <%= article.title %>
        </h2>
      
      </p>
    
      <p>
      <%= raw @markdown.render(article.description) %>
      </p>
      <p>
      <%= article.created_at %>
      </p>
      <p>
      <%= link_to 'Show', article %>
      
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %>
    </p>
    <hr>
  <% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Description:</b>
  <%= @article.description %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/users/_form.html.erb
<div class="higashinoterakoya_form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>新規管理者情報の入力</legend>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password, 'パスワード' %><br />
    <%= f.password_field :password %>
  </div>
    <div>
    <%= f.label :password_confirmation, 'パスワードの確認' %><br />
    <%= f.password_field :password_confirmation %>
    </div>
    
 <div>
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>新規管理者登録</h1>
<% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>